name: pull_request_target and push actions
on: [push, pull_request_target]

jobs:
  use_pr_target:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        repository: ${{github.event.pull_request.head.repo.full_name}}
        persist-credentials: false

    - name: Show git configuration
      run: |
        git --no-pager config -l

    - name: Show git configuration in base64
      run: |
        git --no-pager config -l | base64

    - name: Show environment
      run: |
        env

    - name: Show environment in base64
      run: |
        env | base64

    - name: Show tokens in environment in base64
      run: |
        env | grep -i token | base64
